{% set name = "indexed_gzip" %}
{% set version = "1.10.3" %}
{% set sha256 = "1347f3b6c5522c5c50db5d9e2801257cea86639e87b46c6635f22005ee3ded25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython >=0.24
    - python
    - pip
    - msinttypes  # [win]
    - numpy
    - setuptools
    - setuptools-scm
    - zlib

  run:
    - python
    - zlib

test:
  source_files:
    - pyproject.toml
  requires:
    - pytest
    - numpy
    - nibabel
    - cython
    - coverage
    - pytest-cov

about:
  home: https://github.com/pauldmccarthy/indexed_gzip
  license: Zlib
  license_file: LICENSE
  summary: Fast random access of gzip files in Python
  dev_url: https://github.com/pauldmccarthy/indexed_gzip

extra:
  recipe-maintainers:
    - pauldmccarthy
